export type FontLabCategory = 'Serif' | 'Sans' | 'Display' | 'Mono' | 'Script';

export type FontLabFont = {
  name: string;
  category: FontLabCategory;
};

export const fontLabCatalog: FontLabFont[] = [
  { name: 'Cormorant Garamond', category: 'Serif' },
  { name: 'DM Serif Display', category: 'Serif' },
  { name: 'Bodoni Moda', category: 'Serif' },
  { name: 'Gloock', category: 'Serif' },
  { name: 'Italiana', category: 'Serif' },
  { name: 'Libre Caslon Display', category: 'Serif' },
  { name: 'Playfair Display', category: 'Serif' },
  { name: 'Prata', category: 'Serif' },
  { name: 'Fraunces', category: 'Serif' },
  { name: 'Instrument Serif', category: 'Serif' },
  { name: 'EB Garamond', category: 'Serif' },
  { name: 'Libre Baskerville', category: 'Serif' },
  { name: 'Baskervville', category: 'Serif' },
  { name: 'Lora', category: 'Serif' },
  { name: 'Merriweather', category: 'Serif' },
  { name: 'Spectral', category: 'Serif' },
  { name: 'Cardo', category: 'Serif' },
  { name: 'Literata', category: 'Serif' },
  { name: 'Domine', category: 'Serif' },
  { name: 'Vidaloka', category: 'Serif' },
  { name: 'Alice', category: 'Serif' },
  { name: 'PT Serif', category: 'Serif' },
  { name: 'Ovo', category: 'Serif' },
  { name: 'Bellefair', category: 'Serif' },
  { name: 'Young Serif', category: 'Serif' },
  { name: 'Abril Fatface', category: 'Serif' },
  { name: 'Cormorant Infant', category: 'Serif' },
  { name: 'Zilla Slab', category: 'Serif' },
  { name: 'Arvo', category: 'Serif' },
  { name: 'Roboto Slab', category: 'Serif' },
  { name: 'Inter', category: 'Sans' },
  { name: 'Roboto', category: 'Sans' },
  { name: 'Open Sans', category: 'Sans' },
  { name: 'Montserrat', category: 'Sans' },
  { name: 'Poppins', category: 'Sans' },
  { name: 'Plus Jakarta Sans', category: 'Sans' },
  { name: 'Lato', category: 'Sans' },
  { name: 'Source Sans 3', category: 'Sans' },
  { name: 'Fira Sans', category: 'Sans' },
  { name: 'Public Sans', category: 'Sans' },
  { name: 'Roboto Condensed', category: 'Sans' },
  { name: 'Geist', category: 'Sans' },
  { name: 'Oswald', category: 'Sans' },
  { name: 'Raleway', category: 'Sans' },
  { name: 'Hanken Grotesk', category: 'Sans' },
  { name: 'DM Sans', category: 'Sans' },
  { name: 'Nunito', category: 'Sans' },
  { name: 'Nunito Sans', category: 'Sans' },
  { name: 'Rubik', category: 'Sans' },
  { name: 'Ubuntu', category: 'Sans' },
  { name: 'Manrope', category: 'Sans' },
  { name: 'Outfit', category: 'Sans' },
  { name: 'Work Sans', category: 'Sans' },
  { name: 'Bebas Neue', category: 'Sans' },
  { name: 'IBM Plex Sans', category: 'Sans' },
  { name: 'IBM Plex Sans Condensed', category: 'Sans' },
  { name: 'Archivo', category: 'Sans' },
  { name: 'Archivo Black', category: 'Sans' },
  { name: 'Space Grotesk', category: 'Sans' },
  { name: 'Syne', category: 'Sans' },
  { name: 'Unbounded', category: 'Sans' },
  { name: 'Bricolage Grotesque', category: 'Sans' },
  { name: 'Figtree', category: 'Sans' },
  { name: 'Jost', category: 'Sans' },
  { name: 'Karla', category: 'Sans' },
  { name: 'Quicksand', category: 'Sans' },
  { name: 'Mulish', category: 'Sans' },
  { name: 'Sora', category: 'Sans' },
  { name: 'Urbanist', category: 'Sans' },
  { name: 'Lexend', category: 'Sans' },
  { name: 'Black Ops One', category: 'Display' },
  { name: 'Righteous', category: 'Display' },
  { name: 'Rowdies', category: 'Display' },
  { name: 'Bangers', category: 'Display' },
  { name: 'Creepster', category: 'Display' },
  { name: 'Tektur', category: 'Display' },
  { name: 'Changa One', category: 'Display' },
  { name: 'Lobster Two', category: 'Display' },
  { name: 'Corben', category: 'Display' },
  { name: 'Alfa Slab One', category: 'Display' },
  { name: 'Bowlby One', category: 'Display' },
  { name: 'Honk', category: 'Display' },
  { name: 'Sigmar One', category: 'Display' },
  { name: 'Anybody', category: 'Display' },
  { name: 'Lilita One', category: 'Display' },
  { name: 'Metamorphous', category: 'Display' },
  { name: 'Supermercado One', category: 'Display' },
  { name: 'MedievalSharp', category: 'Display' },
  { name: 'Lobster', category: 'Display' },
  { name: 'Bungee', category: 'Display' },
  { name: 'Rubik Glitch', category: 'Display' },
  { name: 'Comfortaa', category: 'Display' },
  { name: 'Shojumaru', category: 'Display' },
  { name: 'Iceberg', category: 'Display' },
  { name: 'Kranky', category: 'Display' },
  { name: 'Spicy Rice', category: 'Display' },
  { name: 'Cinzel Decorative', category: 'Display' },
  { name: 'Monoton', category: 'Display' },
  { name: 'Fascinate', category: 'Display' },
  { name: 'Limelight', category: 'Display' },
  { name: 'Share Tech Mono', category: 'Mono' },
  { name: 'VT323', category: 'Mono' },
  { name: 'Inconsolata', category: 'Mono' },
  { name: 'Ubuntu Mono', category: 'Mono' },
  { name: 'JetBrains Mono', category: 'Mono' },
  { name: 'Source Code Pro', category: 'Mono' },
  { name: 'Azeret Mono', category: 'Mono' },
  { name: 'Lekton', category: 'Mono' },
  { name: 'IBM Plex Mono', category: 'Mono' },
  { name: 'B612 Mono', category: 'Mono' },
  { name: 'Sacramento', category: 'Script' },
  { name: 'Cookie', category: 'Script' },
  { name: 'Tangerine', category: 'Script' },
  { name: 'Berkshire Swash', category: 'Script' },
  { name: 'Pinyon Script', category: 'Script' },
  { name: 'Sofia', category: 'Script' },
  { name: 'La Belle Aurore', category: 'Script' },
  { name: 'Neucha', category: 'Script' },
  { name: 'Dancing Script', category: 'Script' },
  { name: 'Oooh Baby', category: 'Script' },
];
